spring.application.name=notification-service
server.port=8085

# Logging
logging.level.root=INFO
logging.level.com.foodordering.notificationservice=INFO
logging.level.org.springframework.web=INFO

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
