version: "3.8"

services:

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: fooddb
      MYSQL_USER: fooduser
      MYSQL_PASSWORD: foodpass123
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - food-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  user-service:
    image: rkdocker1800/food-user:v1
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: fooddb
      DB_USERNAME: fooduser
      DB_PASSWORD: foodpass123
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx512m"
    networks:
      - food-network
    deploy:
      replicas: 1

  restaurant-service:
    image: rkdocker1800/food-restaurant:v1
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: fooddb
      DB_USERNAME: fooduser
      DB_PASSWORD: foodpass123
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx512m"
    networks:
      - food-network
    deploy:
      replicas: 1

  order-service:
    image: rkdocker1800/food-order:v1
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: fooddb
      DB_USERNAME: fooduser
      DB_PASSWORD: foodpass123
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx512m"
    networks:
      - food-network
    deploy:
      replicas: 1

  payment-service:
    image: rkdocker1800/food-payment:v1
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: fooddb
      DB_USERNAME: fooduser
      DB_PASSWORD: foodpass123
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx512m"
    networks:
      - food-network
    deploy:
      replicas: 1

  notification-service:
    image: rkdocker1800/food-notification:v1
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: fooddb
      DB_USERNAME: fooduser
      DB_PASSWORD: foodpass123
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx512m"
    networks:
      - food-network
    deploy:
      replicas: 1

networks:
  food-network:
    driver: overlay

volumes:
  mysql-data:
