events {}

http {

    upstream frontend_service {
        server frontend:80;
    }

    upstream user_service {
        server user-service:8081;
    }

    upstream restaurant_service {
        server restaurant-service:8082;
    }

    upstream order_service {
        server order-service:8083;
    }

    upstream payment_service {
        server payment-service:8084;
    }

    upstream notification_service {
        server notification-service:8085;
    }

    server {
        listen 80;

        # React Frontend
        location / {
            proxy_pass http://frontend_service;
        }

        # Backend APIs
        location /api/users {
            proxy_pass http://user_service;
        }

        location /api/restaurants {
            proxy_pass http://restaurant_service;
        }

        location /api/orders {
            proxy_pass http://order_service;
        }

        location /api/payments {
            proxy_pass http://payment_service;
        }

        location /api/notifications {
            proxy_pass http://notification_service;
        }

        # Health Checks
        location = /health/user {
            proxy_pass http://user_service/actuator/health;
        }

        location = /health/restaurant {
            proxy_pass http://restaurant_service/actuator/health;
        }

        location = /health/order {
            proxy_pass http://order_service/actuator/health;
        }

        location = /health/payment {
            proxy_pass http://payment_service/actuator/health;
        }

        location = /health/notification {
            proxy_pass http://notification_service/actuator/health;
        }
    }
}
